-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.libros
(
    id serial NOT NULL,
    titulo text NOT NULL,
    id_autor integer,
    isbn text,
    publicacion text,
    id_categoria integer,
    CONSTRAINT pk_libro PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.autores
(
    id serial NOT NULL,
    nombre text NOT NULL,
    nacionalidad text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    id serial NOT NULL,
    nombre integer NOT NULL,
    descripcion integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.libros
    ADD CONSTRAINT fk_autor FOREIGN KEY (id_autor)
    REFERENCES public.autores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.libros
    ADD CONSTRAINT fk_categoria FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;