-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.productos
(
    id serial NOT NULL,
    nombre text NOT NULL,
    descripcion text,
    precios money,
    stock integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movimiento_stock
(
    id serial NOT NULL,
    nombre text NOT NULL,
    tipo_moviento character(50) NOT NULL,
    cantidad integer NOT NULL,
    product_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.movimiento_stock
    ADD FOREIGN KEY (product_id)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;